name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp

    - name: Download and Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz -O ngrok.tgz
        tar -zxvf ngrok.tgz
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/
        rm ngrok.tgz

    - name: Start xrdp
      run: sudo service xrdp start

    - name: Create Tunnel
      run: ./ngrok tcp 3389
      working-directory: /usr/local/bin/
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
