name: Ubuntu-Xrdp-Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Xrdp and Xfce Desktop
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-goodies
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          echo xfce4-session > ~/.xsession

      - name: Start Xrdp Service
        run: |
          sudo systemctl start xrdp
          sudo systemctl enable xrdp

      - name: Download Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xzvf ngrok-v3-stable-linux-amd64.tgz
          
      - name: Authenticate Ngrok
        run: |
          ./ngrok authtoken 2eY37krFhwW4MTdR9lKn5bUn2hn_6fq5kWUpzB4u5AjxsFSo3

      - name: Update Ngrok to the Latest Version
        run: |
          ./ngrok update
          
      - name: Install xfreerdp
        run: |
          sudo apt-get update
          sudo apt-get install -y freerdp2-x11

      - name: Start X11 Session
        run: |
          sudo startx &
          sleep 5 # Wait for X11 session to start

      - name: RDP Connection
        run: |
          # RDP connection command
          echo "ubuntu" | xfreerdp /v:0.tcp.ngrok.io:14603 /u:ubuntu /p:ubuntu

      - name: Stop X11 Session
        run: |
          sudo pkill X

