name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ngrok-client
        sudo apt-get install -y xrdp
      shell: bash

    - name: Start xrdp
      run: sudo service xrdp start

    - name: Create Tunnel
      run: ngrok tcp 3389
