name: Ubuntu-Xrdp-Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Xrdp and Xfce Desktop
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-goodies
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          echo xfce4-session > ~/.xsession

      - name: Start Xrdp Service
        run: |
          sudo systemctl start xrdp
          sudo systemctl enable xrdp

      - name: Download Ngrok
        run: |
          wget wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-s390x.tgz
          unzip ngrok-v3-stable-linux-s390x.tgz
          
      - name: Authenticate Ngrok
        run: |
          ./ngrok authtoken 2eY37krFhwW4MTdR9lKn5bUn2hn_6fq5kWUpzB4u5AjxsFSo3

      - name: Create Ngrok Tunnel
        run: |
          ./ngrok tcp 3389

      - name: Display Ngrok URL
        run: |
          sleep 5  # Wait for Ngrok to initialize
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

