name: Ubuntu-SSH-Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server

      - name: Start SSH Service
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh

      - name: Check SSH Service Status
        run: |
          sudo systemctl status ssh

      - name: Download Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xzvf ngrok-v3-stable-linux-amd64.tgz
          
      - name: Authenticate Ngrok
        run: |
          ./ngrok authtoken 2eY37krFhwW4MTdR9lKn5bUn2hn_6fq5kWUpzB4u5AjxsFSo3

      - name: Display Ngrok URL for SSH
        run: |
          sleep 5  # Wait for Ngrok to initialize
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

          
      - name: Create Ngrok Tunnel for SSH
        run: |
          ./ngrok tcp 22
